### ISSUE TITLE
Duplicate rfam xrefs for the same accession result in Genoverse crash

### ISSUE THREAD

**Issue by BurkovBA** [RNAcentral/rnacentral-webcode#371] opened 2018-03-29 14:57 UTC
RNAcentral track does not load: http://test.rnacentral.org/rna/URS00009AEC74/10090

See error message here: http://test.rnacentral.org/api/v1/overlap/region/mus_musculus/3:158023741-158111817

Another example of breaking rnacentral track: http://test.rnacentral.org/rna/URS00002B25BC/4896
Another example: http://test.rnacentral.org/api/v1/overlap/region/mus_musculus/7:45545718-45595271

**Comment by blakesweeney** [comment] 2018-04-09 15:58
The new data should not show this problem, reopen this if the issue occurs.

**Comment by BurkovBA** [comment] 2018-04-10 13:49
Still manifests on PRO database: http://test.rnacentral.org/api/v1/overlap/region/mus_musculus/3:158023741-158111817

**Comment by blakesweeney** [comment] 2018-04-10 15:05
Can you tell me which UPI shows this issue?

**Comment by BurkovBA** [comment] 2018-04-10 15:18
Yep, they are u'URS00001CE4E0' and... u'URS00001CE4E0'

**Comment by BurkovBA** [comment] 2018-04-10 15:27
In the meantime, I created a workaround for this, which doesn't assume 1-to-1 relation between xref and accession.

**Comment by blakesweeney** [comment] 2018-04-11 08:13
This seems to be caused by duplicate modomics entries. Poking at the DB shows there are 25 such entries. Not sure what to do about this at the moment, as we don't have plans to update modomics in the near future.

**Comment by AntonPetrov** [comment] 2019-02-15 11:31
The pages referenced above work fine thanks to Boris' workaround so closing this issue.

**Closed by AntonPetrov** 2019-02-15 11:31 UTC
Labels: bug, data problem
